services:
   web:
      build: .
      container_name: bioguard
      ports:
         - "4444:4444"
      restart: unless-stopped
      networks:
         - net

networks:
   net:
      driver: bridge